# Generated by Django 4.1.1 on 2022-10-11 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hanburgesa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=50)),
                ('deskribapena', models.CharField(max_length=100)),
                ('prezioa', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Karritoa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kantitatea', models.IntegerField()),
                ('id_hanburgesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hanburgesa.hanburgesa')),
            ],
        ),
    ]
