# Generated by Django 4.1.1 on 2022-10-11 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanburgesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hanburgesa',
            name='prezioa',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='karritoa',
            name='kantitatea',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
